### PR TITLE
File watcher

### PR DESCRIPTION
**Pull request by Germandrummer92**
- Added a second Thread that watches the specified file for changes and notifies the parser if a change occurs.

It is now possible for the user to check if the underlying xml document is still valid or not. However since the OS might take (and often does take) a long time to update the "LastModified" Attribute on a changed file, and the [WatchService](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchService.html) (my first approach) misses change events if they are executed during the time it takes to process one event, the update to the flag will not be instantaneous (hence the Thread.sleep() in the test).

Since VtdParser keeps the entire parsed Document in memory as a byte array including the indexes, a reparsing is not necessary and external changes don't break our implementation. Not sure if we want the valid flag though as it adds lots of (unneeded) complexity.

### CODE REVIEW

**Comment by Germandrummer92** [comment]
Codacy Fail is due to a issue with lombok generated source.
Travis Fail seems to be because [JPM](http://repo.jpm4j.org/) can't be found??

**Comment by piranha87** [comment]
:+1:

**Comment by bitionaire** [comment]
In general I think it's a good idea to have something like a file watcher for the users of this library, but I see a few issues:

* The watching thread won't terminate, because of the `while(true)` loop 
* There's no way to deactivate the thread (for e.g. performance reasons)
* I think the name `isValid()` is somehow misleading, because an old file version may still be 'valid'.
, but out of date. So 'valid' depends on the use case
* `FileWatcherThread` might be replaced by a simple `file.lastModified() > lastStoredTimestamp` call in `isValid()`, and there's no need for a background thread

I guess I would prefer an optional wrapper for the root `XmlContext` that would update itself on modifications or something like that. Once the user leaves the root context, the old version must be used or an exception should be thrown if that's not possible for technical reasons. Otherwise the complexity would be too high from the users perspective. Just imagine the complexity of nested selection loops. 

@netdevfighter do you mind tipping the scales?

**Comment by Germandrummer92** [comment]
New concept:

*An optional AutoUpdater can be started by calling Fralax.parse(file, true);
*If a rootcontext is created without an autoupdater it can later be started by calling xml.startAutoUpdate() on the root context.
*Once started, the AutoUpdater can be stopped by calling xml.stopAutoUpdate() on the root Context.
*It will check the RootContext for changes and if any occur, automatically call the rootContext.update method
*Both AutoUpdater and RootContext use synchronization measures and should be Thread safe.
*AutoUpdater tests are included

**Comment by bitionaire** [comment]
I just added another alternative for the implementation in the branch [alternative-watcher](https://github.com/1and1/fralax/tree/alternative-watcher). That's what I meant by the _"optional wrapper"_. Though I don't like the addition of another parameter to the `parse(...)` method there, I think it's a bit easier to use & understand. If you like this approach I can add unit tests etc. for it and open a pull request. Otherwise, let's think about yet another way. 👌 ?

**Pull request closed without merging**
